apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
        debugflag: "true"
    spec:
      containers:
      - name: nodejsapp
        image: xxradar/app:3987098891
        ports:
        - containerPort: 8081
