name: FortiDevSec Scanner CI 
on:
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]
 
jobs:
  testing:
   runs-on: ubuntu-latest    
   steps:
   - uses: actions/checkout@v2
   - name: 'Install Node'
     uses: actions/setup-node@v1
   - name: Start app
     run: npm start &
   - name: "Run Test"
     run:  curl http://127.0.0.1:8081
  
  scanning:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SAST
      run: |
       docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
       docker run -i --mount type=bind,source="$(pwd)",target=/scan  registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      
  docker:
    needs: scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: xxradar/app:latest
